### ISSUE TITLE
Breaks forms on non-AMP pages

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-popups#100]
With popups active, if there are pages where AMP is disabled and they contain forms the Popups plugin breaks those forms because it fails to honour the AMP disabled status.

Steps to reproduce:

1. Make sure AMP is enabled and in standard mode
2. Create a page with a form (e.g. using WooCommerce and the My Account page)
3. Ensure AMP is disabled on the form page
4. Visit the page and verify that the form works
5. Verify that "Powered by AMP" does *not* appear in the Console
6. Enable Popups and publish a popup (suggested settings: Sitewide, Bottom placement, 1s timer, Frequency once)
7. Reload the form page
8. Verify that the popup appears
9. Verify that "Powered by AMP" now appears in the console
10. Verify that the form no longer works
11. Verify the following message appears in the console: "Error: Only XHR based (via action-xhr attribute) submissions are supported for POST requests."

**Comment by adekbadek** [comment]
Related: https://github.com/ampproject/amphtml/issues/27638
