### ISSUE TITLE
Frequency options for pop-ups change depending on placement

### ISSUE THREAD

**Issue by iamstevebeatty** [Automattic/newspack-popups#105]
If "inline" is chosen for placement, the frequency choices include "every page."
If any other placement is chosen, you won't see "every page."

This threw off one of our clients who learned to use the feature on inline items, and she was at a loss when looking to have an overlay appear on every page.

@thomasguillot , any UI advice? Is it passe to have unavailable options grayed out and for "every page" say (for inline placement only)?

![Screen Shot 2020-04-17 at 9 49 28 AM](https://user-images.githubusercontent.com/48489469/79582481-6917c480-8091-11ea-9bd5-67416f512b64.png)
![Screen Shot 2020-04-17 at 9 49 08 AM](https://user-images.githubusercontent.com/48489469/79582489-6ae18800-8091-11ea-9327-945027438cca.png)

**Comment by thomasguillot** [comment]
This is kind of related to https://github.com/Automattic/newspack-popups/issues/97 where we need to dissociate the inline placement from the rest. Maybe this will help on the confusion?

I don't think the `SelectControl` component allows disabled options (cc @jeffersonrabb)

_Side note: having a non-inline Pop-up to show on every page is an extremely poor user experience and should be banned. This is why the option is not available._

**Comment by jeffersonrabb** [comment]
> I don't think the SelectControl component allows disabled options (cc @jeffersonrabb)

I learned recently (h/t @adekbadek) that disabled options are supported, as seen in https://github.com/Automattic/newspack-newsletters/blob/master/src/editor/sidebar/index.js#L95-L115
