### ISSUE TITLE
Homepage Posts Block Rendering And Robbery

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-popups#126]
The Homepage Posts block creates a few problems when used in a Campaign. 

1) No posts are shown in the block.
2) If there are other instances of the block on the page, the deduplication logic "robs" them of their posts. 

#### Case 1: Inline placement

<img width="1471" alt="Screen Shot 2020-05-14 at 7 17 46 AM" src="https://user-images.githubusercontent.com/1477002/81929007-32f83280-95b4-11ea-8304-76a78f34f6ff.png">

#### Case 2: Homepage Overlay With No Filtering

Note that all blocks render without posts:

<img width="1471" alt="Screen Shot 2020-05-14 at 7 07 42 AM" src="https://user-images.githubusercontent.com/1477002/81929075-558a4b80-95b4-11ea-904c-2adbd525c233.png">

#### Case 3: Homepage Overlay With Filtering

In this example the Homepage Posts in the campaign is showing posts tagged `events`, and as a result only those posts are robbed from the page's blocks.

<img width="1471" alt="Screen Shot 2020-05-14 at 7 31 37 AM" src="https://user-images.githubusercontent.com/1477002/81929547-3213d080-95b5-11ea-9d57-b0db8a8582d4.png">

**Comment by kariae** [comment]
@claudiulodro for this one the first two cases are fixed already (I guess since I can't reproduce them).

For the third case, I'm wondering if we have a use case for having the same posts on a page and a prompt on the same page?
