### ISSUE TITLE
Homepage Articles Block Occasionally Shows Incorrect Dates With Campaigns Enabled

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-popups#133]
On the https://dailyyonder.com/ staging site, @avcascade observed that some Homepage Articles blocks were showing incorrect publication dates. Disabling Campaigns on the affected page did not resolve the issue, but completely disabling the Newspack Campaigns plugin fixed it. We've seen similar issues before which generally are caused by a `WP_Query` without a corresponding `wp_reset_postdata()`. 

We also found that Campaign insertion logic will be run for every post processed by the Homepage Articles block. In other words https://github.com/Automattic/newspack-popups/blob/master/includes/class-newspack-popups-inserter.php#L113-L158 will execute for every post displayed on a home page, and `is_singular()` will return `true` for all even though the containing page is not a single. 

We patched the problem by adding `is_front_page()` to the checks in https://github.com/Automattic/newspack-popups/blob/master/includes/class-newspack-popups-inserter.php#L114 but we need a more permanent solution so that the Campaigns plugin ignores the loop if it is not the overall page.

**Comment by philipjohn** [comment]
> ignores the loop if it is not the overall page

My guess is that this _should_ be possible by adding a check for `$wp_query->is_main_query()`

**Comment by jeffersonrabb** [comment]
Closing in favor of https://github.com/Automattic/newspack-popups/issues/134.
