### ISSUE TITLE
Top and Bottom Placements Are Too Large

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-popups#135]
The top and bottom Campaign placements often are unusually tall and unsightly. This could be addressed in a number of ways:

- CSS touch-ups to reduce size and spacing.
- New patterns that are better suited to wide/short placements.
- Editor warnings for layouts that are unsuitable to the selected placement.
- Editor styling based on selected placement.

**Comment by claudiulodro** [comment]
Haven't heard any complaints about this recently, so I assume the way they looks is acceptable to our customers.
