### ISSUE TITLE
Error when creating overlay campaign cannot create new campaigns now

### ISSUE THREAD

**Issue by deverman** [Automattic/newspack-popups#139]
I tried to create an overlay campaign and when I saved it I got the error in the attached screen shot.
Attempting to recover the campaign does not work. I copied the html and the error message and pasted below.

I navigated back to the list of campaigns and deleted the campaign. After trying to create a new campaign to start from scratch I still get the same error and so I am stuck with this campaign.

Even though I have closed the browser window I still have the problem.

It seems I am blocked from creating popup campaigns until this is fixed.

<img width="914" alt="Screen Shot 2020-06-08 at 11 33 17" src="https://user-images.githubusercontent.com/802318/83990331-e10cb780-a97b-11ea-981d-d1905f9224fd.png">

```
<!-- wp:image {"id":18415,"sizeSlug":"large"} -->
<figure class="wp-block-image size-large"><img src="https://www.nowshenzhen.com/wp-content/uploads/2020/06/jumpstory-download20200608-031932-1024x683.jpg" alt="Shenzhen concert hall" class="wp-image-18415"/><figcaption>/ Credit Jump Story</figcaption></figure>
<!-- /wp:image -->

```
```
<!-- wp:jetpack/mailchimp /-->

https://www.nowshenzhen.com/wp-content/plugins/gutenberg/build/components/index.js?ver=ee99196b7e809d5c92ce6a56298ad71a:5:320984
Vb@https://www.nowshenzhen.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:104:432
Xi@https://www.nowshenzhen.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:151:138
Xi@[native code]
unstable_runWithPriority@https://www.nowshenzhen.com/wp-includes/js/dist/vendor/react.min.js?ver=16.9.0:26:341
Ae@https://www.nowshenzhen.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:118:180
xi@https://www.nowshenzhen.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:39:148
xi@[native code]

```

**Comment by adekbadek** [comment]
Hi @deverman, sorry for the delay. Is the issue still reproducible? I can't reproduce it, I was able to create a campaign with the markup provided.

**Comment by adekbadek** [comment]
Closing due to lack of response and irreproducibility
