### ISSUE TITLE
Placement in block (not percentage) terms

### ISSUE THREAD

**Issue by iamstevebeatty** [Automattic/newspack-popups#187]
Seeking a finer level of control over placement of inline campaigns

From our friend Doug at Cityside:
"We have the CTA to subscribe on Berkeleyside  after the 8th paragraph, and ads after paragraphs 4 and 15. When we move to Newspack, I think we'd like to have more control over where the CTA displays instead of % into story.

**Comment by claudiulodro** [comment]
We do have manual placement available, not sure what other placement would make sense in that situation. Oaklandside launched a while back and I haven't heard complaints about prompts, so I assume this isn't needed any more.
