### ISSUE TITLE
AMP scripts polyfills for non-AMP pages

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-popups#193]
Currently, to avoid code splitting, [the AMP runtime and other AMP scripts are enqueued](https://github.com/Automattic/newspack-popups/blob/master/includes/class-newspack-popups-inserter.php#L547) by this plugin regardless of whether the page is being served as an AMP page. 

This solution has [caused](https://github.com/Automattic/newspack-popups/issues/151) [various](https://github.com/Automattic/newspack-popups/issues/153) [problems](https://github.com/Automattic/newspack-popups/issues/170) on the front-end.

To put these issues to rest and hopefully avoid any undiscovered or future issues, we should refactor to code split for non-AMP pages, rather than try to force AMP scripts on non-AMP pages.

---

Scripts:
- [X] amp-form
- [x] amp-analytics
- [ ] amp-access (https://github.com/Automattic/newspack-popups/pull/959)
- [x] amp-animation (https://github.com/Automattic/newspack-popups/pull/946)
- [x] amp-bind (https://github.com/Automattic/newspack-popups/pull/946)
- [x] amp-position-observer (https://github.com/Automattic/newspack-popups/pull/946)

**Comment by aschweigert** [comment]
@dkoo it looks like this can be closed, right?

**Comment by dkoo** [comment]
@aschweigert we can probably deprioritize this since I don't think any new issues have been reported as a result of the AMP scripts being loaded on non-AMP pages. #170 is still technically an open issue, but it's an edge case and there's an easy workaround (to disable Campaigns on non-AMP posts that use Jetpack slideshow blocks).

**Comment by yogeshbeniwal** [comment]
These 4 additional JS files are adding to unused Javascript, leading to LCP in Web Vitals. IMHO we should prioritize removing these for overall page experience as @laurelfulford is doing for theme

**Comment by dkoo** [comment]
Since we're moving toward code unification under AMP Plus/JS, we can probably close this as a #wontfix as it won't be relevant in the eventual future where we're not relying on AMP runtime scripts to control prompt display.

**Comment by yogeshbeniwal** [comment]
@dkoo May I know if there is any tracker issue for new approach?

**Comment by dkoo** [comment]
There isn't currently an open issue to track the non-AMP approach. It will likely be more of a milestone than a single issue when the work does happen.

**Comment by adekbadek** [comment]
Just to add some clarity here: this issue is about moving away from AMP (a "JS approach"), but in a way that requires minimal changes. 

If the AMP scripts are polyfilled, the only "AMP" left is the markup (`<amp-access …>` etc). This way the markup can stay the same for both AMP and non-AMP pages, but the JS that the client runs is completely different for both. Right now, it's only partially different.

**Comment by philipjohn** [comment]
Adding this one as another that looks like it's non-AMP related: https://github.com/Automattic/newspack-popups/issues/880
