### ISSUE TITLE
Gray out or eliminate "scroll progress" as a trigger if a popup (top, bottom, center) is chosen for placemnet

### ISSUE THREAD

**Issue by iamstevebeatty** [Automattic/newspack-popups#197]
I really thought that "scroll percentage" DID work on a page as a trigger, but Jeff recently set me straight. 

But "scroll percentage" is still an option when working with a popup, and if it's chosen, it results in the popup not displaying and no indication of what the user has done wrong or how to fix. 

To reproduce,
1. Create new popup campaign, choose placement as Top.
2. Choose the radio button for scroll progress; set it to a low number for ease of testing. 
3. Set frequency to "test mode"
4. Publish the popup. 
5. Click on now-visible "sitewide default" choice (that's another kettle of fish)
6. Update the popup
7. Open a public-facing page, scroll and note lack of popup
8. Edit the popup, changing only the trigger, to timer
9. Open a public-facing page and note popup after a few moments. 

Proposed solution:
Somehow take away the "scroll progress" as an option if a popup placement is chosen. 

In fact, we might not make the "placement" dropdown include Inline at all. It seems a subtle place to make a pretty major choice for display. It adds another piece of UI, but I'd suggest two radio buttons before this, offering either Overlay or Inline, and then choices below fall into place (placement for Overlay; no scroll trigger). This radio-button choice would be prefilled when coming from the Newspack UI because I've already chosen in the wizard to make it an Overlay or Inline. 

![Screen Shot 2020-08-20 at 11 35 11 AM](https://user-images.githubusercontent.com/48489469/90801064-0e120a80-e2db-11ea-8f25-3564e49871b7.png)

**Comment by jeffersonrabb** [comment]
This would only occur on the Homepage or Archives. Scroll progress should work as expected for Overlay Campaigns in Posts. This is because the trigger event is placed after the appropriate paragraph, and the Homepage generally doesn't have paragraphs on it.

**Comment by iamstevebeatty** [comment]
Ah, OK. But my suggestion for separating Overlay from Inline stands. I
realize it's not necessary if coming from the Newspack UI, but sometimes
old habits die hard, and hitting the WPCOM menu just happens.

**Comment by adekbadek** [comment]
Closing as scroll-triggered campaigns now work on Homepage and Archives (#232)
