### ISSUE TITLE
Additional dismiss options for users

### ISSUE THREAD

**Issue by sonjaleix** [Automattic/newspack-popups#204]
Currently the frequency options for campaigns are pretty simple (once, once per day). In the case of the newsletter signup modal we can only pick to show it a single time or every day/time the user comes back, which can feel quite intrusive if a user has already signed up, so not ideal. 

In an ideal scenario, newsletter signups would not display for already signed up users (see ticket #3). another option to consider is adding a secondary dismiss option for the user beyond "I'm not interested" called "maybe later". This would dismiss the modal but bring it back again after a while.

**Comment by jeffersonrabb** [comment]
Hi @sonjaleix, that old ticket was open incorrectly as a whole series of suppression scenarios have already been addressed. Could you take a look at the [campaign suppression docs](https://github.com/Automattic/newspack-popups/pull/27) and see if your use case has already been addressed?

**Comment by sonjaleix** [comment]
thanks @jeffersonrabb for pointing me in this direction! That should be sufficient, but I'll check in with the team.
