### ISSUE TITLE
Inline campaigns: More predictable top of story placement

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-popups#209]
Right now, you can set an inline campaign to appear usually at the top of a story by placing it at 1% down the page. 

However, if your story starts with very short paragraph -- like 1 sentence long -- the campaign will appear after that. 

This does make sense, given that that sentence probably counts as 1%, but it would be great if there was a way to make this seem less random. For example, maybe going off of how long a paragraph is before inserting a campaign, or changing the slider to have a lowest setting of 0 instead of 1, so it's always on top.

**Comment by joeboydston** [comment]
Additionally, perhaps 0% should appear above the headline as requested by Sahan Journal.

![campaigns above headline](https://user-images.githubusercontent.com/22623115/92509610-b83cce00-f1c7-11ea-9dd5-0861e974286a.jpg)

**Comment by adekbadek** [comment]
@joeboydston I've added the before the headline placement request in #260
