### ISSUE TITLE
[bug] once a day campaigns are shown more than once a day

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-popups#220]
h/t to @adekbadek 

To replicate:

1. Campaigns, on master (even before lightweight API)
2. Create an overlay campaign, frequency daily
3. Visit the site, observe the campaign is displayed (or just look at the API response)
4. Reload, observe the campaign is still displayed
5. Without dismissing the campaign, navigate to a new page that does not trigger the bug described in #219, observe that the campaign is still displayed

### Expected behavior

The campaign should be suppressed for the user after being viewed one time, even if not explicitly dismissed.

### Need to also test

Does this affect inline campaigns, too?

**Comment by adekbadek** [comment]
> Does this affect inline campaigns, too?

No, because the bug is cause by only overlay campaigns views not being reported:

https://github.com/Automattic/newspack-popups/blob/17566be67717f4b38d8c7adf2d5f2fed5ea0fed1/includes/class-newspack-popups-model.php#L464
