### ISSUE TITLE
Test Mode Not Working On Non-AMP Pages

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-popups#247]
Campaigns in Test Mode do appear correctly in non-AMP logged in pages. They do work correctly in AMP pages.

Steps to reproduce:

1) Put AMP plugin in Transitional mode.
2) Create an overlay Campaign in Test mode.
3) View any Post while still logged in. Observe the Campaign does not appear.
4) Switch to AMP version of page, observe the Campaign appears correctly.
5) Change the Campaign to Inline and re-try steps 3 and 4. In the non-AMP page the Campaign does appear, but the borders are broken as shown in this screenshot:

<img width="978" alt="Screen Shot 2020-10-18 at 10 57 48 PM" src="https://user-images.githubusercontent.com/1477002/96396531-74a98c80-1195-11eb-829a-32654ace8454.png">

**Comment by adekbadek** [comment]
Fixed in #242 ([comment](https://github.com/Automattic/newspack-popups/pull/242#issuecomment-712062609)) – I did that before seeing this issue. If #242 is not merged soon, I'll open another PR with just these changes.
