### ISSUE TITLE
Popup Sidebar Options Don't Update If Custom Fields Are Enabled

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-popups#25]
If custom fields are enabled in the post type options, updates to the sidebar fields do not stick. 

### Testing

1. Create a new Pop-up.
2. Click the `More Tools & Options` icon in the  upper right (three vertical dots).
3. Click Options. Check "Custom Fields" then Enable & Reload.
4. Make  changes to the Pop-up Settings in  the document sidebar.
5. Save the Pop-up and reload.
6. Observe the changes have been lost.

**Comment by adekbadek** [comment]
I've observed the same with the dek/subtitle feature on `newspack-theme` 🤔

**Comment by dkoo** [comment]
We conferred in #796 and decided that this is something we shouldn't mess with. It may be unintuitive behavior, but not technically a bug.
