### ISSUE TITLE
Segmentation Feature: Mailing List Status

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-popups#250]
There is some campaign suppression logic in place that identifies anonymous IDs as mailing list subscribers but there are some pieces missing.

**Comment by wwanzeller** [comment]
Hi! I have this problem with AmpAnalytics <unknown id>

v0.mjs:2 [AmpAnalytics <unknown id>] Error loading remote config:  https://br.news/wp-content/plugins/newspack-popups/includes/../api/segmentation/index.php?client_id=amp-s3SgImdsuyQ8Y469ikkfvw&post_id=123&custom_dimensions=[]&custom_dimensions_existing_values=[] SyntaxError: Unexpected token m in JSON at position 0

**Comment by adekbadek** [comment]
Hi @wwanzeller 
The response to that `/wp-content/plugins/newspack-popups/includes/../api/segmentation/index.php` request would be helpful, there's an error message there probably. 
Also, this is not the best place to report an issue - please feel free to open one at https://github.com/Automattic/newspack-popups/issues/
