### ISSUE TITLE
Donor status – 3rd party services

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-popups#293]
The segmentation logic will need to be able to determine whether the current user is a donor or member. For sites using WooCommerce this will be fairly straightforward (#249) but sites using third party solutions we'll need to implement new logic. Here's an incomplete list of 3p donation solutions used by Newspack sites which will may to be addressed:

1. [News Revenue Hub](https://fundjournalism.org/) - https://github.com/Automattic/newspack-popups/issues/303
2. [Pico](https://trypico.com/)
3. [Pelcro](https://www.pelcro.com/en), [Piano](https://piano.io/)

**Comment by aschweigert** [comment]
If we decide to partner with Pico and/or Blue Lena then we'll likely want to figure out how to support at least Pico. The others seem much lower priority (for now) but may need to revisit this occasionally and make sure we're supporting the tools most of our publishers are using.

**Comment by adekbadek** [comment]
It's a bit tricky since Pico does not require payments – it can serve as a reg. wall. In that case, the Pico user should not fall into "donors" segmentation. It should rather be another option of "User Account" segmentation:

<img width="313" alt="image" src="https://user-images.githubusercontent.com/7383192/167676900-1dc9e319-5c82-4640-a344-c229be4d7329.png">

**Comment by adekbadek** [comment]
We'll be centralising such data to be on-site, using WC. Integration with these third parties won't be pursued.
