### ISSUE TITLE
Suppress Popup For Mailing List Subscribers

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-popups#3]
Investigate and implement feature that will suppress popups for users who have subscribed to mailing list. May require additions or integration with Jetpack Mailchimp block, Constant Contact plugin, others.

**Comment by sonjaleix** [comment]
We're looking for an option exactly like this! I imagine other publishers would be interested in this feature too.

**Comment by jeffersonrabb** [comment]
This has largely been addressed in https://github.com/Automattic/newspack-popups/pull/173, https://github.com/Automattic/newspack-popups/pull/175, https://github.com/Automattic/newspack-popups/pull/16, and https://github.com/Automattic/newspack-popups/pull/27. Suppression options are documented here: https://newspack.pub/support/engagement/newspack-pop-ups/#suppression
