### ISSUE TITLE
Show a preview of the dismiss button in the editor?

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-popups#311]
Two ideas to explore:

1. Create a custom block to edit the dismiss button text/styles, that always appears at the end of all campaign posts and is undeleteable. Remove the options from the sidebar and use the block attributes instead.

2. Render a simple non-interactive preview of the button as static HTML toward the bottom of the editor content.

Off the top of my head, I don't believe (1) will work because the dismiss button settings are currently stored and rendered as post metadata.

**Comment by thomasguillot** [comment]
> I don't believe (1) will work because the dismiss button settings are currently stored and rendered as post metadata.

Would it be possible to change the way it's stored?

If not, (2) will still be better than what we currently (don't) have 😀
