### ISSUE TITLE
Mailchimp API key storing

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-popups#341]
As is:

Mailchimp API key is cribbed from Newsletters plugin.

To be:

The API key should be stored as a plugin setting, with the Newsletters key as a fallback.

**Comment by kariae** [comment]
@adekbadek does it make sense to put the Mailchimp API key in the [connections screen](https://github.com/Automattic/newspack-plugin/pull/1145)?

**Comment by adekbadek** [comment]
Good idea! This would be a different flow though - a key input instead of an OAuth flow.

**Comment by kariae** [comment]
Closed with #638
