### ISSUE TITLE
Clicking the Newspack logo from editing a campaign leads to hidden campaigns CPT list

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-popups#342]
### Actual

While editing a single campaign, clicking on the Newspack logo will navigate to the Campaigns CPT list with standard WP admin UI. Since https://github.com/Automattic/newspack-plugin/pull/651, this page is hidden from the WP admin menu, so this might be confusing to users who might not know where they are or why they got there.

![Markup on 2020-12-09 at 09:52:15](https://user-images.githubusercontent.com/2230142/101660659-a48e4700-3a04-11eb-902e-d108a1e59d77.png)

### Expected

Clicking on the Newspack logo from a single Campaign edit page should lead to the Campaigns page in the Newspack dashboard, if possible.

**Comment by aschweigert** [comment]
Asana task: https://app.asana.com/0/1200942827698993/1201001433518107

**Comment by dkoo** [comment]
There is a solution to this which I had started implementing in #642, but we closed it in favor of trying to implement a more universal solution in the main plugin (which is still forthcoming).

**Comment by dkoo** [comment]
Fixed by https://github.com/Automattic/newspack-plugin/pull/1482.
