### ISSUE TITLE
Minor Shortcode Improvements

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-popups#353]
As noted in https://github.com/Automattic/newspack-popups/pull/321#pullrequestreview-555473813:

1. The newspack_popups_widget_shortcode_popups_ids option will contain IDs of all Text Widgets, whether or not they contain a campaign shortcode. This isn't damaging, it just means that the option may be larger than necessary. A site would have to have a huge number of Text Widgets for this to cause any real issues!

2. It might make sense to leverage core WordPress shortcode functions for detection and extraction, e.g. get_shortcode_regex. In my testing the regexes in the PR all work well, but using core functions would add a bit of confidence that we're accounting for all possible formatting quirks.

**Comment by claudiulodro** [comment]
AFAIK this hasn't been an issue yet, will revisit if it is.
