### ISSUE TITLE
Feature Suggestion: Campaign Widget Or Block

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-popups#354]
As noted in https://github.com/Automattic/newspack-popups/pull/321#pullrequestreview-555473813, if adding campaigns to widget areas via shortcode turns out to be a common pattern, we should consider creating a dedicated campaign widget and/or block.

**Comment by claudiulodro** [comment]
https://github.com/Automattic/newspack-popups/pull/547
