### ISSUE TITLE
Inactive Campaigns Not Shown In Campaigns Wizard

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-popups#355]
Under certain circumstances (unclear as of now) some inactive campaigns are not shown in the Campaigns Wizard. This was observed on HechingerReport.org, where there are five campaigns yet only three are visible in the wizard.

**Comment by adekbadek** [comment]
@jeffersonrabb is this still an issue, after the wizard overhaul in #767?

**Comment by jeffersonrabb** [comment]
I believe this is still an issue - the fix is in https://github.com/Automattic/newspack-popups/pull/356, but that may be out of date following the overhaul. @dkoo may have a clearer answer?

**Comment by dkoo** [comment]
Yes, I'll need to update that PR (or recreate it) and ask for a re-review.
