### ISSUE TITLE
Releases Don't Include Vendor Directory

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-popups#359]
Releases of the plugin made using the CI automated release workflow don't include the vendor directory. This leads to this fatal on production sites:

```
PHP Fatal error: require_once(): Failed opening required '/wordpress/plugins/newspack-popups/1.21.0/api/segmentation/../../vendor/autoload.php' (include_path='/:.') in /wordpress/plugins/newspack-popups/1.21.0/api/segmentation/class-segmentation-client-data.php on line 13
```

**Comment by dkoo** [comment]
@jeffersonrabb I believe this should do the trick. Let me know if you run into trouble with the alpha testing.
