### ISSUE TITLE
Segment Precedence

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-popups#371]
With the introduction of segmentation it's possible to have multiple campaigns be candidates to show to a single user. For inline campaigns this isn't a big deal, but for overlays and above-header placements this creates a problem. To resolve, we need to determine campaign precedence — in case of a conflict, which campaign "wins?" 

After discussing with @dkoo, @adekbadek and @thomasguillot we settled on this proposed approach:

1) In the Segmentation tag, segment `ActionCard`s can be dragged to establish an order. The order represents precedence from top to bottom.
2) If there is a conflict, the campaign whose segment has the higher weight wins.
3) If there are two campaigns that are in direct conflict, a warning is shown to the admin. This would occur if two published overlay campaigns have the same segment assigned. If the two have category assignments which differ then there's no conflict. These rules also apply to Above Header campaigns.
4) Sitewide default can be removed.

**Comment by thomasguillot** [comment]
> 1. In the Segmentation tag, segment `ActionCard`s can be dragged to establish an order. The order represents precedence from top to bottom.

Let's use the same functionality Core uses to reorganise the Blocks in the Editor so we know it's accessible.
