### ISSUE TITLE
Donor/Subscriber Status Lost After 30-day Data Pruning?

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-popups#378]
This is a question, which may or may not require a fix. Since we purge data after 30 days, does this mean we lose the donor or newsletter subscriber status of anonymous IDs? Put another way, do we only retain donor/subscriber status for 30 days after the event?

**Comment by adekbadek** [comment]
> do we only retain donor/subscriber status for 30 days after the event?

No, the 30 day cap is only on posts read:

https://github.com/Automattic/newspack-popups/blob/25363aed2e61d349bc8eb6831a303fb3a03d70e2/includes/class-newspack-popups-segmentation.php#L426

Other client data (subscriptions, donations) is not purged. It's stored in cache (or the options table).
