### ISSUE TITLE
Possible clash when adding multiple `<script>` tags with the `amp-access` ID

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-popups#413]
There is a possible clash when multiple `<script>`s with the ID 'amp-access' are used on the same page. 

I noticed this issue when testing Pelcro's AMP compatibility -- when using the theme branch with Pelcro's AMP integration on a test site with the campaigns plugin enabled; it seemed like the campaigns script overrwrite the one added to the theme for Pelcro. This can be seen on the Pelcro staging site (ping me for more information about that if needed). 

Steps to reproduce:

1. Start with a site using the [Pelcro integration test branch of the theme](https://github.com/Automattic/newspack-theme/compare/adds/pelcro-integration-test), and with Pelcro connected.
2. View the source of the site when not logged in, and search for `id="amp-access"` -- you should see a section like this, coming from the theme:

```
<script id="amp-access" type="application/json">
{
	"authorization": "https://staging.pelcro.com/integrations/amp/auth/authorization?site_id=240&rid=READER_ID&source_url=SOURCE_URL&return_url=RETURN_URL&ref=DOCUMENT_REFERRER&_=RANDOM",
	"pingback": "https://staging.pelcro.com/integrations/amp/auth/pingBack?site_id=240&rid=READER_ID&source_url=SOURCE_URL&return_url=RETURN_URL&ref=DOCUMENT_REFERRER&_=RANDOM",
	"login": {
		"sign-in": "https://staging.pelcro.com/integrations/amp/login?site_id=240&rid=READER_ID&source_url=SOURCE_URL&return_url=RETURN_URL",
		"sign-out": "https://staging.pelcro.com/integrations/amp/logout?site_id=240&rid=READER_ID&source_url=SOURCE_URL&return_url=RETURN_URL"
	},
	"authorizationFallbackResponse": {
		"isAuthorized":false,
		"isSubscribedToSite":false
	}
}
</script>
```

3. Enable the Campaigns plugin.
4. View source again, and search for `id="amp-access`.
5. Instead of finding the above script, it will turn up one for Campaigns instead. Because of this, the links added by the theme as part of the Pelcro integration don't work:

```
<script id="amp-access" type="application/json">
{"namespace":"popups","authorization":"https:\/\/pelcro-newspack.newspackstaging.com\/wp-content\/plugins\/newspack-popups\/includes\/..\/api\/campaigns\/index.php?cid=CLIENT_ID(newspack-cid)&ref=DOCUMENT_REFERRER&popups=[]&settings={\"suppress_newsletter_campaigns\":true,\"suppress_all_newsletter_campaigns_if_one_dismissed\":true,\"suppress_donation_campaigns_if_donor\":false,\"newspack_newsletters_non_interative_mode\":false,\"all_segments\":[],\"newspack_popups_active_campaign_group\":false}&visit={\"post_id\":\"294\",\"categories\":\"\",\"is_post\":false}","noPingback":true}		
</script>
```

It seems like only one of these scripts is allowed on the page at a time, but I'm not sure if AMP is stripping one out, or something else.

**Comment by kariae** [comment]
We can have multiple access providers, and for this, I changed how we inject the amp-access script.
I propose to handle the [amp-script injection](https://github.com/Automattic/newspack-theme/commit/229bfe33f28d3a14993ff43741320d75b95df081) in the [theme header](https://github.com/automattic/newspack-theme), and whenever we need to add a new provider (e.g. [from Campaigns](https://github.com/Automattic/newspack-popups/commit/ac57708071cbfb2c4965afdab4ec77a079627d9b) or Pelcro) we just use the new filter like this:

```php
add_filter(
	'newspack_campaigns_amp_access_providers',
	function( $providers_config ) {
		$providers_config[] = [
                        // provider configuration details
		];
		return $providers_config;
	}
);
```

Since we don't have a current need for this, I'll let the proposed branches standing (in case we need this in future) and close this for now :)
