### ISSUE TITLE
Pop up not styled well on 404 page.

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-popups#42]
I'm not sure whether this is an issue with newspack-popups or with the theme. If you get served a pop up while on the 404 screen, it doesn't look right.

On 404:
<img width="1474" alt="Screen Shot 2020-01-20 at 5 50 12 PM" src="https://user-images.githubusercontent.com/7317227/72768897-b62ced00-3bad-11ea-9a4d-d3a2fcae45b0.png">

On regular single/page:
<img width="1110" alt="Screen Shot 2020-01-20 at 5 52 44 PM" src="https://user-images.githubusercontent.com/7317227/72768908-bd53fb00-3bad-11ea-99a6-4f2d24e7d510.png">

**Comment by thomasguillot** [comment]
Looks like the stylesheet isn't rendered.

cc @jeffersonrabb

**Comment by adekbadek** [comment]
Cannot reproduce:

![image](https://user-images.githubusercontent.com/7383192/96868359-3a2e4100-146e-11eb-9e72-54d9481e3dcf.png)
