### ISSUE TITLE
Add a debug tool

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-popups#421]
Given how extensive the options are now for showing campaigns, it can be pretty easy to get in a situation where you _think_ a campaign should show up but it doesn't, and figuring out why can be pretty hard.

It might be worthwhile having a debug tool where users could select  a) a campaign, b) a URL and b) a segment and a report will show what criteria are assessed and what campaigns match those criteria. Knowing why campaigns _don't_ show will be equally useful.

**Comment by adekbadek** [comment]
> Knowing why campaigns don't show will be equally useful.

That's added in #539
