### ISSUE TITLE
"Uncategorized" Category Hidden In UI But Breaks Insertion Logic

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-popups#447]
If a prompt has the "uncategorized" category assigned it [will be suppressed in the UI](https://github.com/Automattic/newspack-popups/blob/master/includes/class-newspack-popups-inserter.php#L591-L596 ). However, the presence of this category will cause the prompt to be inserted like a categorized prompt, only in content bearing the same term. 

Ideally the solution is to ignore the "uncategorized" category in `retrieve_category_overlay_popups()`, or remove this tag every time the prompt is saved.

 If this proves difficult, a short-term half fix would be to remove the logic that hides the category, which at least will make it easier to diagnose this issue.

**Comment by dkoo** [comment]
I think the ideal solution here would be to ensure that prompts never get _automatically_ assigned the site's default category (usually "Uncategorized" but it can be set to any category in WP admin > Settings > Writing). There are still use cases I can imagine where a site might actually want to show certain prompts only on Uncategorized pages or whatever category is set to the default.

I would think most publishers would create most of their prompts without any category, so I've been considering this the default user story. The WP behavior of automatically assigning the default category to new uncategorized posts conflicts with this.

**Comment by adekbadek** [comment]
It gets worse:
1. Rename your "Uncategorized" to something else
2. Deactivate a prompt
3. Activate it - observe it now has the category assigned

**Comment by dkoo** [comment]
Yes, that's just WP behavior, right? If you publish a post with no category, it automatically assigns the default category. So the hiding of "Uncategorized" was definitely ill-advised on my part because that default category can be named anything, not just "Uncategorized". I still think the ideal solution would be to somehow prevent the default category from ever being automatically assigned to prompts.
