### ISSUE TITLE
New inline placement option: Archives

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-popups#450]
For inline prompts, we have two placement options:

1. In article content
2. Above header

"In article content" obviously only lets editors place inline prompts in actual post content. "Above header" can appear on posts, pages, or archive pages, but only at the very top of the page.

What about adding a third placement option—"In archive pages"—that has a slider similar to the "in article content" slider to choose position? For archive pages, this slider would represent the number of archive items to render before the prompt, with a minimum of 1 (so the prompt can never appear first) and a reasonable maximum of say, 20. If there aren't enough items on an archive page to meet this setting, then the prompt gets rendered at the end of the list. If the archive list is empty, then the prompt doesn't get rendered.

These prompts will follow category filtering rules: if the prompt has categories assigned, it will only appear on archive pages for those categories. If no categories are assigned, then they can appear on any archive page.

Another idea, maybe not necessary: there could also be an option to repeat the prompt—so if the "number of items before prompt" setting is 3, and the "repeat" option is enabled, then the prompt appears after every three items until the end of the archive page list.

Mockup:

<img width="275" alt="Screen Shot 2021-02-17 at 9 55 39 AM" src="https://user-images.githubusercontent.com/2230142/108239023-b6781e80-7106-11eb-99d2-c35e263e2e38.png">

**Comment by tmmbecker** [comment]
CTNewsJunkie was looking for this feature and actually didn't realize that it's doesn't happen automatically.

**Comment by allykmyta** [comment]
Will author archive pages be included? If so, are we able to add a filter to toggle specific archive pages for the prompt (tags, categories, author)?

**Comment by kariae** [comment]
The proposed PR does include all the archive pages (author archive page too). 

A toggle filter for the archive pages would be very good in this case, I'll add it :) Thank you for the suggestion.

**Comment by kariae** [comment]
<img width="281" alt="Screen Shot 2021-09-23 at 2 37 39 PM" src="https://user-images.githubusercontent.com/26310353/134500403-3557f9c1-c08d-4589-957c-bf04f5504d69.png">

once https://github.com/Automattic/newspack-popups/pull/621 is shipped :)
