### ISSUE TITLE
[Question] No frequency settings for Inline prompts?

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-popups#472]
@jeffersonrabb and @adekbadek: @brianboyer mentions that he believes frequency options aren't relevant for inline, above-header, or manually placed prompts, only overlays. For non-overlays, the standard behavior should be "until dismissed."

I think this warrants deeper discussion—what are your thoughts?

**Comment by adekbadek** [comment]
Hm, hard to say without some use cases. I think it's nice to have a possibility of a subtle once-a-day above-header prompt. But I don't have a strong opinion here. As long as "Until dismissed" is the default I don't think it's confusing to have more frequency options.

**Comment by dkoo** [comment]
I agree that I like having the options, but I'd say let's table this until we have some feedback from actual publishers.

**Comment by adekbadek** [comment]
Ok, let's reopen if we get some feedback.
