### ISSUE TITLE
"Category exclusion" segmentation?

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-popups#480]
We had a publisher with two prompts:

* Prompt A should be shown to readers with certain favorite categories
* Prompt B should be shown to everyone else

Should we consider adding a "category exclusion" segment to cover this use case? For this specific publisher, we created a segment for Prompt B that applied to all readers (min. 1 article read), which accomplished what they wanted, but I can see the argument for a segmentation criterion where you choose categories, and only if the reader's favorite categories are _not_ in that list do they match the segment.

**Comment by adekbadek** [comment]
Alternatively, we could add an "inverse segment" option to segment criteria - instead of picking specific criteria, user could choose another segment to serve as a "negative segment".

**Comment by dkoo** [comment]
That's an interesting idea...what if you choose an inverse segment to inverse? 🤯

**Comment by tmmbecker** [comment]
This seems pretty similar to #68. Excluding by tag has also come up.

**Comment by claudiulodro** [comment]
Closing as a dupe of #68
