### ISSUE TITLE
AmpAnalytics <unknown id> #bug

### ISSUE THREAD

**Issue by wwanzeller** [Automattic/newspack-popups#544]
I have this problem with AmpAnalytics <unknown id>

v0.mjs:2 [AmpAnalytics <unknown id>] Error loading remote config:  https://br.news/wp-content/plugins/newspack-popups/includes/../api/segmentation/index.php?client_id=amp-s3SgImdsuyQ8Y469ikkfvw&post_id=123&custom_dimensions=[]&custom_dimensions_existing_values=[] SyntaxError: Unexpected token m in JSON at position 0
#bug

**Comment by adekbadek** [comment]
Hi @wwanzeller , have you created the [configuration file](https://github.com/Automattic/newspack-popups#config-file)? 
Also, if any PHP errors are logged, that would be useful, as well as the response to the request mentioned in the error message (you can see that in the browser's network tab).

**Comment by adekbadek** [comment]
Closing due to lack of response. Feel free to re-open, though!
