### ISSUE TITLE
Target campaigns by post type

### ISSUE THREAD

**Issue by gamebits** [Automattic/newspack-popups#567]
Some plugins (such as [Newspack Podcasts](https://github.com/Automattic/newspack-podcasts)\) register their own CPTs. Customers should be able to target campaigns to specific post types such as these.

The current workaround is to apply a dedicated category or tag to each CPT and then target a campaign using those terms.

**Comment by dkoo** [comment]
In terms of UI, I would suggest the following:

1. In the single prompt editor screen, a new sidebar panel called "Post Types" that lists all of the post types a prompt can be inserted into. This would look similar to the "Post Types" sidebar panel for Homepage Posts, except all post types would be selected by default. At least one post type must be selected here.

<img width="276" alt="Screen Shot 2021-06-30 at 5 18 31 PM" src="https://user-images.githubusercontent.com/2230142/124042974-45efe100-d9c7-11eb-9beb-13a06d40a1ee.png">

2. On the Campaigns dashboard, adding "Post Types" with a comma-delimited list of the post types in each prompt's action card. (This message area is getting kind of crowded, but I can't think of a better place to display this info on the dashboard.)

Then, when we go to insert the prompt on the front-end, we'd have to add a check of the prompt's "post types" meta. By default, this would be all post types that support Campaigns.

cc @adekbadek @thomasguillot @miguelpeixe

**Comment by adekbadek** [comment]
> On the Campaigns dashboard, adding "Post Types" with a comma-delimited list of the post types in each prompt's action card.

@dkoo - I wonder if it's worth the effort. This seems like a rarely-used feature, so maybe settings post types when editing prompt will suffice?

**Comment by dkoo** [comment]
> This seems like a rarely-used feature, so maybe settings post types when editing prompt will suffice?

Definitely something we could add later if we feel it's warranted.
