### ISSUE TITLE
Campaigns + no AMP cause Web Stories block not to work

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-popups#569]
When Google's [Web Stories](https://wordpress.org/plugins/web-stories/) block is embedded on a site with AMP disabled and Campaigns running, clicking on the different stories loads a black screen, but not the story itself.

If you either enable AMP on the page the block is embedded in, or turn off campaigns on that specific page, the stories will load as expected. 

When they're not working, you get this error in the Console:

`Uncaught Error: Render timeout waiting for service amp-story-render to be ready.​​​`

Originally reported by a publisher, but I was able to recreate on a pretty vanilla Newspack site (just running the theme, Web Stories and Campaigns plugins). 

## Steps to reproduce

1. Install the [Web Stories](https://wordpress.org/plugins/web-stories/) plugin and create one story
2. Enable the Campaigns plugin and disable AMP
3. Add the Web stories block to a page
4. Click on one of the stories
5. Get just a black screen

If you disable Campaigns on that page, or enable AMP, when you click on a story, it will open in a full-screen popup.

I'm guessing this has something to do with the partial-AMP state that Campaigns + no AMP creates on a site; I'm not sure if this is the correct place to file this, so please let me know if it should be moved!

**Comment by aschweigert** [comment]
20 sites have the web stories plugin installed, presumably this only affects pages with the web stories block on them...so feels low-ish priority but something worth investigating.

**Comment by dkoo** [comment]
Reopened by #995.
