### ISSUE TITLE
[WP 5.8] Campaigns plugin causes editor crash in widget block editor

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-popups#570]
In the new blocks-based widget editor, the Campaigns plugin may cause an editor crash with the following JS error message:

```
TypeError: _wordpress_edit_post__WEBPACK_IMPORTED_MODULE_4__ is undefined
    PopupsSettingsPanel webpack:///./src/document-settings/index.js?:31
```

This seems to be caused by the use of `PluginDocumentSettingPanel` in a non-post editor context [here](https://github.com/Automattic/newspack-popups/blob/master/src/document-settings/index.js).

Since the option to "Disable prompts on this post or page" is irrelevant for the widgets editor, we should probably not enqueue that JS file on the widgets editor page [here](https://github.com/Automattic/newspack-popups/blob/master/includes/class-newspack-popups.php#L388-L401).

**Comment by dkoo** [comment]
Strangely, I couldn't replicate on my local environment, only on a site running the plugin via the latest release package.

**Comment by laurelfulford** [comment]
> Strangely, I couldn't replicate on my local environment, only on a site running the plugin via the latest release package.

Also odd: I ran into this issue on one of two sites running the plugin via the latest release package - I'm not sure why it was okay on one site, but not the other.

**Comment by dnalla1928** [comment]
> In the new blocks-based widget editor, the Campaigns plugin may cause an editor crash with the following JS error message:

Also experience this same result.  Not sure if it relevant or not, but one of my sites with all plugins disabled, but the Newspack theme enabled, the widget page flashes the welcome message.  Console throws: 
`react-dom.min.js?ver=16.13.1:125 TypeError: e.widgets.every is not a function`

**Comment by dkoo** [comment]
This does not seem to happen when viewing Widgets in the Customizer.
