### ISSUE TITLE
[WP 5.8] Show prompts in Customizer preview

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-popups#577]
WP 5.8 introduces blocks-based widgets, which can be edited in the Customizer. This includes prompts via the Custom Placement and Single Prompt blocks. We made a decision early on to not show prompts to logged-in users, so prompts placed in widget areas via the Customizer's widget editor are not shown in the preview.

### The fix

The simple solution would be to show the first prompt that matches the block attributes—published or unpublished, regardless of segment—in the Customizer preview. Or if not a prompt, then a placeholder element that suggests a prompt would be rendered in this widget area. I'd suggest we do this as an MVP for the 5.8 release on July 20.

An enhancement to this would be to use the existing segmentation preview functionality from the Campaigns dashboard in the Customizer as well, and let admins choose which segment they're previewing as within the Customizer. This is a much more complex solution that would also require new UI inside the Custom Placement and Single Prompt blocks, when edited in the Customizer only. I'm not sure this would be worth the extra effort over the simpler solution.

**Comment by adekbadek** [comment]
> Or if not a prompt, then a placeholder element that suggests a prompt would be rendered in this widget area.

+1

**Comment by miguelpeixe** [comment]
> I'd suggest we do this as an MVP for the 5.8 release on July 20.

+1
