### ISSUE TITLE
PHP Warning: Offset not contained in string

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-popups#618]
No reproducible example yet, but it appears that the offset parameter passed to [`stripos` call](https://github.com/Automattic/newspack-popups/blob/91d48a4ae09afb468367db9857eb425e33b668d1/includes/class-newspack-popups-inserter.php#L267) can be incorrect. PHP logs a warning then:

```
Offset not contained in string
```

It's not an error, just a warning. But it should be fixed.

**Comment by adekbadek** [comment]
Should be fixed by applying the classic-content insertion from https://github.com/Automattic/super-cool-ad-inserter-plugin/pull/65

**Comment by dkoo** [comment]
This should have been fixed by #647; closing.
