### ISSUE TITLE
E-commerce links from Mailchimp don’t appear to influence segments

### ISSUE THREAD

**Issue by aschweigert** [Automattic/newspack-popups#662]
Asana task: https://app.asana.com/0/1200942827698993/1201001429681511/f
Details: https://docs.google.com/document/d/1s83l3e_kwYnMziNjN4Fhju3lwlrKEMbX6eUuPpZrb7U/edit#heading=h.6bvdy5a8d4rk

**Comment by kariae** [comment]
@aschweigert I tried to reproduce this on a local site, but this looks fine. 

- I created a few segments (Subscribers /Donors / Subscribers and Donors) and generated prompts accordingly.
- I subscribed and send myself a newsletter (to get the link with the right query parameters).
- Visited a post page and the prompts were showing as expected.
- Same for donor prompts.

If you don't mind, I'll close this, for now, please feel free to re-open it if you can reproduce the issue.
