### ISSUE TITLE
Single-prompt preview does not work for custom placement prompts

### ISSUE THREAD

**Issue by aschweigert** [Automattic/newspack-popups#663]
Asana: https://app.asana.com/0/1200942827698993/1201001433518097
Details: https://docs.google.com/document/d/1yaRwAQirSrCyNdjqlyGdeALLwrNfrJEkZsKvwM66e_w/edit#heading=h.k9fuwuqo7sh2

**Comment by dkoo** [comment]
The "include unpublished prompts in segment previews" was actually fixed in #613. The Asana task details another bug where Custom Placement previews aren't shown correctly in individual prompt previews, so I'm renaming the task accordingly.
