### ISSUE TITLE
Form submission events not working in some cases

### ISSUE THREAD

**Issue by aschweigert** [Automattic/newspack-popups#664]
Asana: https://app.asana.com/0/1200942827698993/1201001433518030
Details: https://docs.google.com/document/d/18dBs-2PiYre8msDaZswRdciSmqExVfMrN9GgpaO9qsg/edit#heading=h.jnbaztf59mwl

**Comment by dkoo** [comment]
I was able to replicate this on a test site. I can see that the "Load" and "Seen" events are firing, but not the "Submit" event. Will investigate further.

**Comment by dkoo** [comment]
This has been released in v1.47.2. Closing.
