### ISSUE TITLE
Implement a custom dimension for primary category

### ISSUE THREAD

**Issue by aschweigert** [Automattic/newspack-popups#676]
Asana: https://app.asana.com/0/1200942827698993/1201001433518056/f
Details: https://docs.google.com/document/d/18dBs-2PiYre8msDaZswRdciSmqExVfMrN9GgpaO9qsg/edit#heading=h.ekjcszu1izwd

**Comment by dkoo** [comment]
@aschweigert I started investigating this, and I remembered that we [implemented a change](https://github.com/Automattic/newspack-plugin/pull/727) a while ago that checks if a post has a primary category, and if so, only reports that single category as the `Category` custom dimension. Is that enough for the spirit of this requirement?

If not, we can remove that behavior and add another custom dimension just for Primary Category, but I wanted to make sure it's what we want. Doing so might be a breaking change for publishers who are using the Category custom dimension already.

**Comment by aschweigert** [comment]
I think that probably works for what we need here actually. The behavior without Yoast (comma separated list of categories sent over as the custom dimension) is definitely a headache but since we have so many sites using Yoast it seems like the easiest path here is to lean into that implementation and not both to send both the comma-separated list AND a primary category. I'll close this for now and we can revisit if it turns out that there's a reason we would want to have both.

**Comment by dkoo** [comment]
Thanks for clarifying! Continuing to send just the one category dimension definitely does lighten the payload a bit.
