### ISSUE TITLE
Add ability to preview prompts for unpublished campaigns

### ISSUE THREAD

**Issue by aschweigert** [Automattic/newspack-popups#683]
Currently, I can click the preview on the “…” link on each individual prompt to see what it'd look like, but when I click the <eyeball> on the segment, my not-yet-published prompts do not appear. Being able to see what everything looks like in concert, *before* I publish is essential for QAing my work.

Asana: https://app.asana.com/0/1200942827698993/1201001433518122
Details: https://docs.google.com/document/d/1yaRwAQirSrCyNdjqlyGdeALLwrNfrJEkZsKvwM66e_w/edit#heading=h.rg1lv4h767c

**Comment by aschweigert** [comment]
@adekbadek you mentioned this should have been fixed in https://github.com/Automattic/newspack-popups/releases/tag/v1.39.0, can we call this one resolved or should we do a bit more testing?

**Comment by adekbadek** [comment]
Exactly. Resolved by this PR to be specific: https://github.com/Automattic/newspack-popups/pull/613
