### ISSUE TITLE
 Tell me how many people might actually be targeted in a segment

### ISSUE THREAD

**Issue by aschweigert** [Automattic/newspack-popups#686]
Many sites are creating segments with very narrow parameters that likely reach very few people. Ideally we'd show an estimate of the segment size based on their traffic, newsletter list size, etc but this might be nearly impossible in practice and thus better addressed via documentation/training/etc.

Asana: https://href.li/?https://app.asana.com/0/1200942827698993/1201001433518132/f
Details: https://docs.google.com/document/d/1yaRwAQirSrCyNdjqlyGdeALLwrNfrJEkZsKvwM66e_w/edit#heading=h.8oy3ww1x84mp

**Comment by dkoo** [comment]
@aschweigert we do show this metric of "viewability" on the segment pages, which is based on historical data (e.g. what percentage of readers in the past 30 days are known to match this segment?). How might we improve the messaging and/or usefulness?

<img width="1081" alt="Screen Shot 2022-04-22 at 10 36 39 AM" src="https://user-images.githubusercontent.com/2230142/164757377-40f44220-ae7d-4679-8012-eb2beae11a8f.png">

**Comment by aschweigert** [comment]
@dkoo Ah, I see @adekbadek commented in Brian's doc and this issue was specific to reveal (due to a timeout issue) so I think we can probably close this one for now.
