### ISSUE TITLE
Make it easier for logged-in users to preview and QA prompts

### ISSUE THREAD

**Issue by aschweigert** [Automattic/newspack-popups#687]
UPDATE (3/9/22): per the discussion below and the many requests we've received from publishers, let's remove the logged-in admin check and make the behavior the same regardless of whether a user is logged in or not.

---

As @adekbadek noted, this might already be working fine but seems to be confusing so we'd probably want to start with some user-testing here and see if we can improve the segment preview UI to make it clearer how this is working.

Asana: https://app.asana.com/0/1200942827698993/1201001433518127
Details: https://docs.google.com/document/d/1yaRwAQirSrCyNdjqlyGdeALLwrNfrJEkZsKvwM66e_w/edit#heading=h.dt0seyczvadv

**Comment by gamebits** [comment]
Noozhawk has requested the feature.

**Comment by supersusie** [comment]
On behalf of Noozhawk: I can see why you might not want to see popups and overlays a bunch of times if you're a logged in WP user, but it would definitely be helpful to see inline and archive page campaigns for layout purposes.

**Comment by aschweigert** [comment]
I was just going through the responses to [the recent survey](https://docs.google.com/spreadsheets/d/1PnP9ObMfG6t_LjMldlZ1h97P7J3laqZhIWaVdnPDmp4/edit?resourcekey#gid=2005844274) we ran about Campaigns and there were a couple responses in there getting at the same thing. 

While it might be pretty annoying for editors to get a popup on every pageview (for example), it's probably best that they experience the site as close to a regular user would experience it as possible.

So it seems like we should probably make the default behavior the same regardless of whether a user is logged in or not. Optionally, maybe we could have a setting that suppressed some or all prompts for logged in users if they start to get too annoying (though that could also be a good signal that maybe a site might want to tone them down a bit :)

**Comment by adekbadek** [comment]
+1 for dropping the logged-in-admin check. The site owner should have a front-end experience that's as close to the reader's as possible.

**Comment by allykmyta** [comment]
PB has also requested this feature.

**Comment by aschweigert** [comment]
This would only be for inline prompts, when an article is previewed from the block editor, show the prompt for all logged in users.

**Comment by adekbadek** [comment]
The prompts would only be visible in the block editor, then? That's different than what I've understood here – I was thinking that the prompts would be displayed when the logged-in user is browsing the front-end of the site.

**Comment by aschweigert** [comment]
> I was thinking that the prompts would be displayed when the logged-in user is browsing the front-end of the site.

When @dkoo and I talked this over, we thought starting with showing prompts when you preview a post/page would make the most sense. The main reason being that some sites might want to segment by logged-in state (see #746) so this has the potential to get weird (I think?) if we were to just remove that check entirely. Let me know what you think @adekbadek, maybe we should have another quick chat about this before implementing.

**Comment by adekbadek** [comment]
> The main reason being that some sites might want to segment by logged-in state (see https://github.com/Automattic/newspack-popups/issues/746) so this has the potential to get weird (I think?) if we were to just remove that check entirely.

I'd rather say that removing the check should be a requirement for implementing logged-in-state segmentation. Right now, no prompts are displayed for logged-in users. With such segmentation, the check would have to be overridden for the prompts in such segment. This makes things even more complicated, unnecessarily. 

> starting with showing prompts when you preview a post/page would make the most sense

I agree – granted it's about _previewing_, not _editing_:

<img width="314" alt="image" src="https://user-images.githubusercontent.com/7383192/158582774-c08d5e26-fe31-4eea-815d-4aaf4654a270.png">

IMO, when _editing_ a post, an editor should not expect to see non-editorial content such as prompts, ads, or cookie banners. When _previewing_ a post, the editor should have an experience that's as close to the reader's as possible. Same when they browse the front-end while logged-in. 

One consideration here is analytics – we might not want to report views & interactions made by editors (a certain type of logged-in users).

**Comment by aschweigert** [comment]
That all makes sense to me...does that work for you @dkoo?

> we might not want to report views & interactions made by editors

If this is easy to do it might be worth excluding author and above from *all* tracking since this tends to skew GA data somewhat, particularly for smaller sites. For big sites it wouldn't be very significant but not loading GA for logged in users above a certain role is generally a good practice for news sites to avoid any pollution in the data GA collects since sites really only care about end user behavior, not their own staff.

**Comment by yogeshbeniwal** [comment]
Site kit provide options to exclude Users that can write posts.

**Comment by dkoo** [comment]
I started working on this on Thursday and it's relatively straightforward to make prompts appear to admin/editor users who are logged in, just like they're readers. This means they'll only see prompts with segments they match. My thought was, maybe this is the preferred behavior when they're simply browsing around the site, but if they're previewing a post from the block editor, would it be worth showing _all_ the inline prompts regardless of segment, so that they can get a sense of whether the content will conflict with any prompt for any readers?

As for analytics, we could try to more simply not print the AMP analytics config for logged-in editor/admin users, which should prevent events from getting tracked in those sessions.
