### ISSUE TITLE
Trigger automatically revert to Timer

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-popups#694]
Even after setting popup trigger to scroll progress

- Revisiting popup editing page shows Trigger set to Timer
- Settings are mixed up as shown in below screenshot

![](https://user-images.githubusercontent.com/7325107/143531656-4692a0ed-7b05-4f35-ac47-51ad568e5f98.png)

**Comment by aschweigert** [comment]
duplicate issue, closing in favor of #748
