### ISSUE TITLE
Inline placement provides uneven layout in archive pages

### ISSUE THREAD

**Issue by allykmyta** [Automattic/newspack-popups#708]
Creating an inline prompt with placement in archive pages results in uneven spacing between the prompt and articles on the archive page.

<img width="531" alt="Markup 2021-11-30 at 11 08 26" src="https://user-images.githubusercontent.com/35075802/144112140-cb8b06b5-0aef-4efc-af88-0b2cb30f322d.png">

p1638297736467200/1638292922.462300-slack-C01C378QWRX

**Comment by dkoo** [comment]
Perhaps unrelated, but visible in the above screenshot: [this CSS](https://github.com/Automattic/newspack-popups/blob/master/src/view/patterns.scss) seems to be causing the subscription-related block patterns to render off-center in inline and overlay contexts. Perhaps these styles were once relevant but they don't seem to be helping at all anymore, and I'd recommend deprecating it (after testing the effects).
