### ISSUE TITLE
Plugin name / WP Admin labels inconsistent

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-popups#71]
Steve noticed the plugin is called Newspack Popups (no hyphen), but the UI refers to them as Pop-ups (with hyphen).

I checked with Editorial, and A8c's styleguide has it as 'pop-up'; I'm not sure it makes sense to change the folder name at this point but is it possible to change the plugin name in the UI?

(I'm not 100% sure whether this will cause issues if the plugin is submitted to the .org plugin repo in the future, since -- at least with themes -- the name and slug have to match).

**Comment by adekbadek** [comment]
Closing, as this features are now referred to as "Campaigns". We'll see if we're gonna have to change to repo and release zip names, too.
