### ISSUE TITLE
Campaigns removes Podcast Block play bar

### ISSUE THREAD

**Issue by akmyta** [Automattic/newspack-popups#729]
When the Newspack Campaign plugin is active, it removes the play bar in the Podcast Block from front-end of the site and also seems to remove the Cover Art (this can be seen as a logged out viewer or in incognito). Disabling prompts for a page or post doesn't resolve the issue, the play bar will only reappear when the Campaigns plugin is deactivated.

How it appears when Campaigns plugin is active:
<img width="1010" alt="Markup 2021-12-09 at 12 45 54" src="https://user-images.githubusercontent.com/35075802/145476073-98c82bfc-737f-460e-825e-2dd261605324.png">

How it appears when Campaigns plugin is deactivated:
<img width="871" alt="Markup 2021-12-09 at 12 42 23" src="https://user-images.githubusercontent.com/35075802/145476118-4725eaa0-b17b-4f30-9363-33c05fab30f5.png">

Reported by Atavist.

**Comment by dkoo** [comment]
Note that the fix implemented in #771 no longer seems to work. The issue as described now seems to occur with the main Newspack Plugin and Newsletters as well.

**Comment by adekbadek** [comment]
Not reproducible anymore. Most probably this was caused by AMP-related code, which is no more here.
