### ISSUE TITLE
Support post revisions

### ISSUE THREAD

**Issue by gamebits** [Automattic/newspack-popups#731]
A change to a Newspack Campaign can have significant consequences (good or bad!) for a publisher's click/conversion rate. Knowing what change was made, when, and by whom would be useful.

To that end, adding support for [WordPress post revisions](https://wordpress.org/support/article/revisions/) to the Campaigns CPT would be helpful.

**Comment by aschweigert** [comment]
Yeah, this is a good suggestion! This is mostly covered by #688 so going to merge this with that one.
