### ISSUE TITLE
Segment by logged-in state

### ISSUE THREAD

**Issue by gamebits** [Automattic/newspack-popups#746]
### Issue

Segments can currently target whether a visitor is subscribed to a newsletter, and whether they're a paid subscriber. But what about users who have created accounts without subscribing? Or users who have not created accounts at all?

### Use cases

Creating a free account can confer functionality, such as on sites that have WordPress’s “Users must be registered and logged in to comment” feature enabled. Publishers want to run campaigns that target anonymous visitors, excluding users who are already logged in.

Publishers also want to target users who have created free accounts, encouraging them to become paid members. The campaign language to upsell a registered user might be different from a campaign targeting an anonymous user.

### Proposal

It would be helpful if Newspack Campaigns could account for these scenarios by segmenting users by their logged-in state.

**Comment by aschweigert** [comment]
Initially let's just do this for logged-in WP users who are subscribers or woo customers only (not admins, editors, etc).

As a bonus look into whether we can support this for Pico users who are authenticated (probably via cookie?)
