### ISSUE TITLE
Conflict with Liveblog plugin

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-popups#749]
## To reproduce

1. Install the [Liveblog](https://wordpress.org/plugins/liveblog/) plugin 
2. Create a post and enable Liveblog on it
3. (Disable AMP on the post if enabled)
4. Observe the Liveblog text editor on the front-end is broken – copying & pasting, inserting links, among others do not work
5. Disable Campaigns for this post, or disable the `newspack-campaigns` plugin
6. Observe the liveblog editor works fine

**Comment by aschweigert** [comment]
liveblog is currently used by 14 sites, since there's a workaround (disabling campaigns on liveblog posts) marking this as low priority for now

**Comment by dkoo** [comment]
Reopened by #995.
