### ISSUE TITLE
Multiple "popups" on the same post

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-popups#77]
As far as I can tell, the insertion logic allows for either an inline or a modal popup, but not both on one post and not multiple inline popups. 

I think most sites have a setup like the following:
- Newsletter inline CTA
- One or more inline ad units (e.g. 3 and 6 paragraphs in)
- Newsletter/Donate modal

The solution IMO is the inline popups should not count towards the popup for the page. Let people insert as many inline "popups" as they want.

Further question: should people inject inline ads with this tool, or continue with SCAP?

Thoughts @jeffersonrabb, @thomasguillot?

**Comment by jeffersonrabb** [comment]
Yes! This immediately came to mind while working on https://github.com/Automattic/newspack-popups/issues/77. This raises a few questions:

- Presumably we get rid of the concept of "Sitewide Default" for Inline Popups?
- If we are enabling multiple inline pop-ups per story, things get quite a bit more complex. Are you convinced this part is required? 
- Is this a blocker for https://github.com/Automattic/newspack-popups/issues/77?

**Comment by claudiulodro** [comment]
Assuming you meant #76, I don't think this is a blocker for it at all. The "Every page" frequency will be a good compliment to this.

> If we are enabling multiple inline pop-ups per story, things get quite a bit more complex. Are you convinced this part is required?

I think it's only required if we want to use this for ad units, otherwise I can't imagine someone needs more than 1 inline thing per post (and we probably want to discourage it if so). I'm not sure if this is the best place to set up inline ad units, though; an ad unit would be weird with the "I'm not interested" bit at the bottom. Probably not required.

**Comment by jeffersonrabb** [comment]
> I think it's only required if we want to use this for ad units

I don't think Ads are an appropriate use of Pop-ups, as we would have two competing sets of visibility logic.
