### ISSUE TITLE
Auto-placement within content

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-popups#78]
The new inline popups feature is great, and is really useful for adding calls to action within articles. This is a feature that would be even more useful if placements could be automatic, much like the Super Cool Ad Inserter can be used to automatically place ads within content.

For example, an advert added with Newspack's Advertising feature can be placed within the content automatically by adding the widget to Ad Inserter's sidebar area.

A simple addition to this plugin would be to make the popups available via a widget. Alternatively, each popup could be placed within the content via the settings in the popup editor itself.

The result for publishers would be the ability to automatically place newsletter subscription forms, donation appeals and membership promotions within every single article at a suitable spacing an interval. This would really help publishers to better engage their readership.

**Comment by claudiulodro** [comment]
I think with WP 5.8's block-widgets feature, you could use SCAIP to insert arbitrary block-based content within other content. That would work well.
