### ISSUE TITLE
Segmentation: Add tracking for Gravity Forms newsletter sign ups

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/newspack-popups#791]
We've recently discovered that quite a few Newspack sites (12-15) are using a Gravity Forms form to collect newsletter sign-ups. Because the subscriber tracking is only connected to the Jetpack Mailchimp block or the MC4WP form, there is no way to track subscribers on these sites.

**Comment by aschweigert** [comment]
Gravity Forms is our preferred form solution for more complex forms and Jetpack Forms is our recommend solution for very simple use-cases.

MC4WP is in wide use so we still want to support this as well.

Let's make sure we can support all three and accurately attribute/track form submissions.

Additionally, we should add an option for a site admin to specific an arbitrary classname to the form to enable tracking so we can potentially support other form solutions that sites might already be using.
