### ISSUE TITLE
Inline placements should not be dismissable

### ISSUE THREAD

**Issue by aschweigert** [Automattic/newspack-popups#822]
From Reveal: 

We expected the newsletter prompt on the mid-homepage to always appear, regardless if you're a subscriber, because it's targeted to the "everyone" group. But that's not what we see -- once you've used the prompt, it goes away and we just see a blue rectangle.

Here's our hypothesis: Once someone has used a prompt (eg signed up for our newsletter, or made a donation), it's considered "dismissed", and the *frequency* setting on the campaign prompt disables it.

If our hypothesis checks out, it would be great to have a new frequency setting different than "dismissed" for non-popup prompts, like "always" -- prompts that are baked into the UX of the site that don't go away after use.

Here's the blue rectangle we see where the midhomepage prompt should appear:

![image](https://user-images.githubusercontent.com/490703/157744362-6410c26b-f5fc-44ef-b990-9332dbaedd47.png)

Here's what we expected to see on the midhomepage prompt:

![image-1](https://user-images.githubusercontent.com/490703/157744386-28ea2c8e-12e3-4791-b7aa-32e4f5934cc8.png)

**Comment by aschweigert** [comment]
This is sort of #doingitwrong (in my opinion) because really these sorts of persistent elements are not a great use case for campaigns (article bottom recirculation is another great example), but since we allow them (for now) it would probably be best to make inline elements persistent and have them not obey the "until dismissed" setting we use for popups and other more obtrusive prompts.

**Comment by dkoo** [comment]
Sounds to me like the best interim solution would be two steps:

1. Don't automatically suppress newsletter or donation related prompts as allowed in the Campaigns plugin settings page) if the prompts are rendered by a Custom Placement or Manual block. These prompts are meant to be more or less static and should only be suppressed if manual suppression by the reader is allowed.
2. Make the "non-suppressable" option more evident to site editors by adding a toggle option to the Dismiss button UI—if suppression is toggled "off" then no dismiss button will be rendered (same as the current behavior if the Dismiss Button Text field is left blank).
