### ISSUE TITLE
Dismiss button in wrong location in WordPress 6.0 RC

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-popups#864]
When using the WP 6.0 RC, if you create a new prompt, the Dismiss button previews above the content as soon as you start editing it:

![image](https://user-images.githubusercontent.com/177561/166989475-efd916af-265e-4ca5-9feb-a349dd3e77dc.png)

It displays in the correct location on the front-end, and this issue doesn't appear to happen when editing existing prompts. If you publish your new prompt and exit and reenter the editor, the issue corrects itself.

## Steps to recreate

1. Start on a test site running the latest WP 6.0 RC
2. Create a new Overlay prompt
3. Edit the empty paragraph block that's there. 
4. Note that the Dismiss text and paragraph block swap locations.

**Comment by dkoo** [comment]
Closing as https://github.com/Automattic/newspack-popups/pull/866 has been merged.
