### ISSUE TITLE
NTG events not sent for campaigns to Google Analytics

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-popups#868]
NTG events are not sent for campaigns to Google Analytics. News Tagging Guide custom events is enabled in settings.

Detailed debugging shows that events are sent for other plugins such as social share. AMP is completely disabled and not used anymore for this case.

**Comment by dkoo** [comment]
@yogeshbeniwal so that I understand the issue: on a site not using AMP at all, the Campaigns plugin doesn't fire NTG events? Does it fire _any_ events? How about on a site that is running AMP? Could you provide exact steps to replicate so I know what to look for?

**Comment by yogeshbeniwal** [comment]
@dkoo It doesn't fire any events? Campaigns are shown to visitors but neither events are sent to GA, nor campaign analytics shows any events in graph. 

Not sure about website running with AMP, it was working fine recently with AMP transitional mode. Have completely disabled AMP now.

**Comment by dkoo** [comment]
Thanks for clarifying—we'll look into this.

**Comment by dkoo** [comment]
@yogeshbeniwal I'm unable to replicate on a new test site. Replication steps:

1. On the new test site, connect Site Kit and Analytics.
2. Set up Campaigns plugin and publish a prompt containing a Jetpack Mailchimp newsletter signup block.
3. Disable AMP plugin.
4. In a new session, view the prompt.
5. In Dev Tools > Network, observe a request to `https://google-analytics.com/?collect` with an event category of `NTG newsletter` and event label of `newsletter modal impression 1`.
6. In the GA dashboard, under Realtime, observe an event captured matching the request.

<img width="1626" alt="Screen Shot 2022-05-16 at 2 35 26 PM" src="https://user-images.githubusercontent.com/2230142/168679074-f35431e2-addb-4a47-8901-315e5e2c5143.png">

If you're seeing different results, can you specify what's different in your setup from my testing steps?

**Comment by yogeshbeniwal** [comment]
Thank you @dkoo. Disconnecting and reconnecting analytics in Site kit solved the issue.
