### ISSUE TITLE
Lookup subscriber status in ESP by email, if logged in

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-popups#893]
If a WP user logs in, and they are not marked as a subscriber in segmentation, ESP should be queried to see if they are a subscriber. They might've been signed up via other medium than the site.

**Comment by adekbadek** [comment]
This serves a similar purpose as https://github.com/Automattic/newspack-popups/issues/901, but is more robust – the reader could've subscribed using a different method, or before Newspack plugins were active.

**Comment by adekbadek** [comment]
@dkoo I'm wondering about the point at which this should happen – and it seems to me that the moment an email is supplied to Reader Activation handlers (registration/donation/etc) is the most relevant. WDYT?

**Comment by dkoo** [comment]
@adekbadek Miguel and I discussed this a bit offline. Our current thinking is that an action hook that fires with the email address as soon as the reader provides it would be useful for both this and other proposed features.
