### ISSUE TITLE
Non-AMP click events not always tracked via GA

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-popups#894]
Click events fired by prompts in non-AMP pages seemingly aren't reported all the time. This may be because of the async nature of reporting events via JS, and if links lead to a new page, the browser is stopping JS execution. This would be a similar problem like we saw in https://github.com/Automattic/newspack-popups/issues/664.

**Comment by adekbadek** [comment]
With the switch to GA4, these custom events are no longer tracked.
