### ISSUE TITLE
Segmentation: handle pre-authentication

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-popups#903]
## As is 

The segmentation can target users who have logged in.

## To be

With the addition of pre-authentication (https://github.com/Automattic/newspack-plugin/pull/1655), ~a segmentation option should be added to allow targeting pre-authenticated/non-pre-authenticated readers~ the "has user account" segment option should also target the pre-authenticated users.

**Comment by dkoo** [comment]
With the data refactor in progress, a reader is known to have an account when we've logged at least one reader event with a `user_account` type value. We could log the pre-auth state with a `user_account` event and `preauth` context value without a user ID value, and identify pre-auth readers separately from registered readers, if we wanted to. Is there a publisher user story that describes a need to do this, though? e.g. showing a prompt to pre-auth readers who haven't completed registration to encourage them to finish signup

**Comment by miguelpeixe** [comment]
> We could log the pre-auth state with a user_account event and preauth context value without a user ID value

I like this

> Is there a publisher user story that describes a need to do this, though?

Even if we don't have a specific story for pre-auth readers or a segment for them, they should at least be treated as "has user account". I'm assuming the standard behavior would be to treat them as anonymous, since they are not officially logged in.

**Comment by adekbadek** [comment]
> I'm not sure how helpful it is to segment pre-authenticated readers differently than the current "has user account". I think we can be optimistic about that as well and assume that a pre-authenticated reader has an account.

Agreed. Pre-authenticated user will get a user account anyway.
