### ISSUE TITLE
Can't exclude prompts by more than one category

### ISSUE THREAD

**Issue by iamstevebeatty** [Automattic/newspack-popups#932]
In the Advanced Settings panel of a prompt, there are fields for excluding categories and tags. 

However, the category field won't take multiple entries. Publisher would like to exclude from multiple categories. 

https://user-images.githubusercontent.com/48489469/182924174-8cb0ca7f-8dbd-4c8a-8da6-6d4c1f7c96bb.mov

**Comment by tmmbecker** [comment]
CalMatters reported this as well. @dkoo could you take a look?

**Comment by dkoo** [comment]
Confirmed—will need to refactor this bit of UI to allow multiple selections.
